#!/bin/bash

closure --charset utf8 \
--compilation_level SIMPLE_OPTIMIZATIONS \
--js jquery.1.7.min.js \
--js jquery.lightbox-0.5.js \
--js bootstrap-transition.js \
--js bootstrap-dropdown.js \
--js bootstrap-tooltip.js \
--js bootstrap-popover.js \
--js bootstrap-carousel.js \
--js jquery.cookie.js \
--js jquery.ui.custom.js \
--js markitup/jquery.markitup.js \
--js markitup/sets/markdown/set.js \
--js comments.js \
--js core.js \
--js_output_file scripts.combined.min.5.js